SabrinaAssya/iloveou

- Gemfile.lock
- app/controllers/reviews_controller.rb
- app/views/reviews/edit.html.erb
- app/views/reviews/index.html.erb
- app/views/reviews/new.html.erb
- app/views/reviews/show.html.erb
- config/routes.rb
- test/controllers/reviews_controller_test.rb
ajout de 
- controller
- views
> create new branch

- app/controllers/activities_controller.rb
- app/views/activities/edit.html.erb
- app/views/activities/new.html.erb
- test/controllers/activities_controller_test.rb
Added controller and views for activities
> added controller/views

- app/models/review.rb
> review validates

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/reviews/index.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
ajout
- form corrigé 
- redirection corrigée
- save les reviews
- index reviews à jour avec les nouvelles create reviews
> routes et saves reviews

- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- config/routes.rb
> Activities edit

- app/controllers/itineraries_controller.rb
- app/views/itineraries/index.html.erb
- db/migrate/20230209184712_add_rating_to_itinerary.rb
- db/schema.rb
- db/seeds.rb
+ Ajout du trie par popularité avec ajout du rating dans le model itinéraires. 
+ Ajout du trie par date de création des itinéraires 
+ Modification de la seed ajout du rating + sleep pour avoir des timstamps différents
> Trie sur les itinéraires

- app/controllers/activities_controller.rb
- app/models/category.rb
- db/migrate/20230204102548_create_categories.rb
- db/migrate/20230211093749_remove_references_category_from_activities.rb
- db/migrate/20230211094507_drop_category.rb
- db/schema.rb
- test/models/category_test.rb
Modified db: 
- removed categories from table activities
- removed table categories
> modified database

- app/controllers/itineraries_controller.rb
- app/models/itinerary.rb
- app/views/itineraries/index.html.erb
- db/migrate/20230214185452_change_price_type.rb
- db/schema.rb
- db/seeds.rb
+ connexion des filtre tries et search station + modif seed
> search big updapte

- app/views/pages/dashboard.html.erb
- db/schema.rb
Modified view dashboard changes no activities to no itineraries yet. 
Added button edit to my itineraries
> Modified view dashboard

- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
added redirection drop down and footer
> few changes in redirections

- app/models/itinerary.rb
- app/models/user.rb
- db/seeds.rb
added dependent destrroy for favorites on user and itineraries models
added seed for favorites
> favorites relation & seed

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_itineraries.scss
- app/views/itineraries/index.html.erb
> front itineraries

- app/assets/stylesheets/components/_itineraries.scss
- app/views/itineraries/index.html.erb
> still on itineraries front

- app/assets/stylesheets/components/_indexcarditineraries.scss
Changement sur la partiel des card pour index itineraires. Conflit avec les balises html des autres pages, j'ai retiré le css "opacity". Merci de faire attention au nommage de vos class / balises
> navbar changes

- app/assets/stylesheets/components/_top_itineraries.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/itineraries/new.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
- app/views/shared/_newreview.html.erb
- app/views/shared/_top_itinerary_card.html.erb
- db/seeds.rb
- package.json
- yarn.lock
Added back images that are local in our app. Need to work on it so they also work on heroku.
Worked a bit on the css of the homepage, carousel not finished.
Reworked the seed by adding images for all activities and added more reviews.
> images back and some css for the homepage

- db/seeds.rb
Remise en conformité des durations dans la seed d'itinéraires
> modif seed duration

- app/controllers/favorites_controller.rb
- app/javascript/controllers/favorite_heart_controller.js
- app/javascript/controllers/index.js
- app/views/itineraries/index.html.erb
- config/routes.rb
Worked on Ajax to favorite hearts
> heart favorites

- app/assets/stylesheets/components/_indexcarditineraries.scss
- app/views/itineraries/index.html.erb
Almost finished front index iitineraries
> front almost finished

- app/assets/stylesheets/components/_indexcarditineraries.scss
- app/controllers/activities_controller.rb
- app/views/activities/index.html.erb
- app/views/itineraries/index.html.erb
Modified activity index, Waiting for the button to be added in show itineraries
> Stimulus heart

- app/assets/stylesheets/components/_reviews.scss
- app/assets/stylesheets/components/_showitineraries.scss
- app/javascript/controllers/openreviewform_controller.js
- app/views/itineraries/show.html.erb
Displayable review form on itineraries show
fixed a few buttons border that were making surrounding elements move on hover
> Reviews on itinerary

- app/assets/stylesheets/components/_indexcarditineraries.scss
> cards finished

- app/assets/stylesheets/components/_showitineraries.scss
- app/views/itineraries/show.html.erb
alignement des containers dans la show
> aligement des éléments

- app/assets/stylesheets/components/_home_search.scss
- app/assets/stylesheets/pages/_home.scss
- app/javascript/controllers/tom_select_controller.js
- app/models/itinerary.rb
- app/views/shared/_home_search.html.erb
search for homepage done with some fixing of carousel
> Home search

- app/assets/stylesheets/components/_reviews.scss
- app/assets/stylesheets/components/_top_itineraries.scss
- app/views/itineraries/show.html.erb
- app/views/shared/_top_itinerary_card.html.erb
reviews corrected with avatar and name of the user who wrote it
> Index rework
